name: Build and Push to GHCR

on:
  push:
    branches: [main]
    tags: ["v*"]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Extract metadata (tags, 8-char SHA)
        id: meta
        run: |
          echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          echo "SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.SHORT_SHA }}
            ${{ steps.meta.outputs.GIT_TAG != '' && format('{0}:{1}', env.IMAGE_NAME, steps.meta.outputs.GIT_TAG) || '' }}